module.exports = {
  preset: "ts-jest/presets/js-with-ts",
  globals: {},
  transform: {},
  // roots: ['<rootDir>/src'],
  rootDir: "..",
  verbose: true,
  // setupFiles: ["react-app-polyfill/jsdom"],
  // setupFilesAfterEnv: ["<rootDir>/tests/configs/setupTests.ts"],
  testMatch: ["<rootDir>/**/*.{spec,test}.{js,jsx,ts,tsx}"],
  // testEnvironment: "jsdom",
  // testRunner: "<rootDir>/node_modules/jest-circus/runner.js",
  transformIgnorePatterns: ["/node_modules/"],
  moduleDirectories: ["node_modules"],
  modulePaths: [],
  moduleNameMapper: {
    "^.+\\.module\\.(css|sass|scss)$": "identity-obj-proxy",
    "\\.(jpg|jpeg|png|gif|eot|otf|webp|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$":
      "identity-obj-proxy",
    "\\.(css|scss)$": "identity-obj-proxy",
    "\\.svg": "<rootDir>/tests/configs/svgMock.js",
  },
  setupFilesAfterEnv: ["<rootDir>/tests/configs/setupTests.js"],
  moduleFileExtensions: ["js", "ts", "tsx", "json", "jsx", "node"],
  // watchPlugins: [
  //   "jest-watch-typeahead/filename",
  //   "jest-watch-typeahead/testname",
  // ],
  resetMocks: true,
  bail: true,
  // snapshotSerializers: ["enzyme-to-json/serializer"],
  // reporters: [
  //   "default",
  //   [
  //     "./node_modules/jest-junit",
  //     {
  //       suiteName: "jest tests",
  //       outputDirectory: ".",
  //       outputName: "junit.xml",
  //       uniqueOutputName: "false",
  //       classNameTemplate: "{classname}-{title}",
  //       titleTemplate: "{classname}-{title}",
  //       ancestorSeparator: " › ",
  //       usePathForSuiteName: "true",
  //     },
  //   ],
  //   [
  //     "./node_modules/jest-html-reporters",
  //     {
  //       pageTitle: "Test Report",
  //       publicPath: "./",
  //       filename: "test-report.html",
  //       expand: true,
  //     },
  //   ],
  // ],
  // testResultsProcessor: "jest-junit",
};
